/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 --instanceall Bar.glb
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";

const context = createContext();
export function BarInstances({ children, ...props }) {
  const { nodes } = useGLTF("/models/bar.glb");
  const instances = useMemo(
    () => ({
      Node: nodes.Node,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props} castShadow receiveShadow>
      {(instances) => (
        <context.Provider value={instances}>
          {children}
        </context.Provider>
      )}
    </Merged>
  );
}

export function Bar(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <instances.Node />
    </group>
  );
}

useGLTF.preload("/models/bar.glb");
